name: "Bug Report"
description: Report a bug or issue with Grassator.
title: "[Bug Report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        This form is only for submitting bug reports. If you have a usage question
        or are unsure if this is really a bug, please use the [Discussions](https://github.com/noctisynth/Grassator/discussions) section instead.

        Also try to search for your issue - it may have already been answered or even fixed in the development branch.
        However, if you find that an old, closed issue still persists in the latest version,
        you should open a new issue using the form below instead of commenting on the old issue.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen?
        Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner.
        Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: |
        Please provide a step-by-step guide to reproduce the issue. If possible,
        provide screenshots or files like videos that show the issue.
    validations:
      required: true
  - type: input
    id: repro
    attributes:
      label: Reproduce link
      description: "Please provide a simplest reproduction of the problem, provide the URL of the project:"
      placeholder: Paste link here
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
      placeholder: |
        Describe what happened in detail.
    validations:
      required: true
